extends:
  import: classic
  file: go/pipeline.yaml
env:
- name: DOCKER_CONFIG
  value: /home/jenkins/.azure-docker/
- name: AZURE_CONFIG_DIR
  value: /home/jenkins/.azure
pipelines:
  pullRequest:
    setup:
      steps:
      - name: docker-config-mkdir
        command: mkdir -p $DOCKER_CONFIG
      - name: docker-config-cp
        command: cp -L /home/jenkins/.docker/config.json $DOCKER_CONFIG/config.json
      - name: azure-login
        command: rpm --import https://packages.microsoft.com/keys/microsoft.asc && echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo && yum install azure-cli -y && curl -L https://aka.ms/acr/installaad/bash | /bin/bash && cp /usr/local/bin/docker-credential-acr-linux /usr/local/bin/docker-credential-acr && az login --identity && az acr login -n  $DOCKER_REGISTRY
    build:
      steps:
      - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
    promote:
      steps:
      - dir: /home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME/charts/preview
        steps:
        - sh: make preview
        - sh: jx preview --app $APP_NAME --dir ../..

  release:
    setup:
      steps:
      - name: docker-config-mkdir
        command: mkdir -p $DOCKER_CONFIG
      - name: docker-config-cp
        command: cp -L /home/jenkins/.docker/config.json $DOCKER_CONFIG/config.json
      - name: azure-login
        command: rpm --import https://packages.microsoft.com/keys/microsoft.asc && echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo && yum install azure-cli -y && curl -L https://aka.ms/acr/installaad/bash | /bin/bash && cp /usr/local/bin/docker-credential-acr-linux /usr/local/bin/docker-credential-acr && az login --identity && az acr login -n  $DOCKER_REGISTRY
    build:
      steps:
      - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
    promote:
      steps:
      - dir: /home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME/charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
        - comment: release the helm chart
          sh: jx step helm release
        - comment: promote through all 'Auto' promotion Environments
          sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
