extends:
  import: classic
  file: javascript/pipeline.yaml  
env:
- name: DOCKER_CONFIG
  value: /home/jenkins/.azure-docker/
- name: AZURE_CONFIG_DIR
  value: /home/jenkins/.azure
pipelines:
  pullRequest:
    setup:
      steps:
      - name: docker-config-mkdir
        command: mkdir -p $DOCKER_CONFIG
      - name: docker-config-cp
        command: cp -L /home/jenkins/.docker/config.json $DOCKER_CONFIG/config.json
      - name: azure-login
        image: mcr.microsoft.com/azure-cli 
        command: az
        args:
        - login
        - --identity
      # - name: azure-acr-login
      #   image: mcr.microsoft.com/azure-cli
      #   command: az acr login -n $DOCKER_REGISTRY
    build:
      steps:
      - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
        name: container-build
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
        name: post-build
    promote:
      steps:
      - dir: ./charts/preview
        steps:
        - sh: make preview
          name: make-preview
        - sh: jx preview --app $APP_NAME --dir ../..
          name: jx-preview

  release:
    setup:
      steps:
      - name: docker-config-mkdir
        command: mkdir -p $DOCKER_CONFIG
      - name: docker-config-cp
        command: cp -L /home/jenkins/.docker/config.json $DOCKER_CONFIG/config.json
      - name: azure-login
        image: mcr.microsoft.com/azure-cli 
        command: az
        args:
        - login
        - --identity
      # - name: azure-acr-login
      #   image: mcr.microsoft.com/azure-cli
      #   command: az acr login -n $DOCKER_REGISTRY
    build:
      steps:
      # - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
      #   name: container-build
      - name: container-build
        command: /kaniko/executor
        args:
        - --cache=true
        - --cache-dir=/workspace
        - --context=/workspace/source
        - --dockerfile=/workspace/source/Dockerfile
        - --destination=$DOCKER_REGISTRY/$ORG/$APP_NAME:${inputs.params.version}
        - --cache-repo=$DOCKER_REGISTRY/todo/cache
        - --skip-tls-verify-registry=$DOCKER_REGISTRY
        - --verbosity=trace
        dir: /workspace/source
        image: gcr.io/kaniko-project/executor:v0.24.0
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
    promote:
      steps:
      - dir: ./charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --batch-mode --version v\$(cat ../../VERSION)
          name: changelog
        - comment: release the helm chart
          sh: jx step helm release
          name: helm-release
        - comment: promote through all 'Auto' promotion Environments
          sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
          name: jx-promote
