extends:
  import: classic
  file: javascript/pipeline.yaml  
containerOptions:
  env:
  - name: DOCKER_CONFIG
    value: /home/jenkins/.azure-docker/
pipelines:
  pullRequest:
    options:
      containerOptions:
        env:
        - name: DOCKER_CONFIG
          value: /home/jenkins/.azure-docker/
    setup:
      steps:
      - name: azure-login
        image: mcr.microsoft.com/azure-cli 
        command: az
        args:
        - login
        - --identity
      # - name: copy-docker
      #   command: cp -d /home/jenkins/.docker/config.json $DOCKER_CONFIG
    build:
      steps:
      - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
        name: container-build
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
        name: post-build
    promote:
      steps:
      - dir: ./charts/preview
        steps:
        - sh: make preview
          name: make-preview
        - sh: jx preview --app $APP_NAME --dir ../..
          name: jx-preview

  release:
    options:
      containerOptions:
        env:
        - name: DOCKER_CONFIG
          value: /home/jenkins/.azure-docker/
    setup:
      steps:
      - name: azure-login
        image: mcr.microsoft.com/azure-cli 
        command: az
        args:
        - login
        - --identity
      # - name: copy-docker
      #   command: cp -d /home/jenkins/.docker/config.json $DOCKER_CONFIG
    build:
      steps:
      - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
        name: container-build
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
    promote:
      steps:
      - dir: ./charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --batch-mode --version v\$(cat ../../VERSION)
          name: changelog
        - comment: release the helm chart
          sh: jx step helm release
          name: helm-release
        - comment: promote through all 'Auto' promotion Environments
          sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
          name: jx-promote
