extends:
  import: classic
  file: javascript/pipeline.yaml  
pipelines:
  default:
    pipeline:
      options:
        containerOptions:
          volumeMounts:
          - mountPath: /home/jenkins/.docker
            name: volume-dot-docker
          - mountPath: /home/jenkins/.docker-confs
            name: volume-0
        volumes:
        - name: volume-dot-docker
          emptyDir: {}
        - name: volume-0
          secret:
            secretName: jenkins-docker-cfg
    stages:
      name: preSetup
      steps:
      - name: install-azure-cli-rpm
        command: rpm --import https://packages.microsoft.com/keys/microsoft.asc
      - name: install-azure-cli-repo
        command: |
          echo -e "[azure-cli]
          name=Azure CLI
          baseurl=https://packages.microsoft.com/yumrepos/azure-cli
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo'
      - name: install-azure-cli-yum
        command: yum install -y azure-cli
  pullRequest:
    build:
      steps:
      - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
        name: container-build
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
        name: post-build
    promote:
      steps:
      - dir: ./charts/preview
        steps:
        - sh: make preview
          name: make-preview
        - sh: jx preview --app $APP_NAME --dir ../..
          name: jx-preview

  release:
    build:
      steps:
      - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
        name: container-build
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
    promote:
      steps:
      - dir: ./charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --batch-mode --version v\$(cat ../../VERSION)
          name: changelog
        - comment: release the helm chart
          sh: jx step helm release
          name: helm-release
        - comment: promote through all 'Auto' promotion Environments
          sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
          name: jx-promote
