extends:
  import: classic
  file: pipeline.yaml
agent:
  label: jenkins-maven
  container: maven
pipelines:
  pullRequest:
    setup:
      steps:
      - name: docker-config-mkdir
        command: mkdir -p $DOCKER_CONFIG
      - name: docker-config-cp
        command: cp -L /home/jenkins/.docker/config.json $DOCKER_CONFIG/config.json
      - name: azure-login
        command: rpm --import https://packages.microsoft.com/keys/microsoft.asc && echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo && yum install azure-cli -y && curl -L https://aka.ms/acr/installaad/bash | /bin/bash && cp /usr/local/bin/docker-credential-acr-linux /usr/local/bin/docker-credential-acr && az login --identity && az acr login -n  $DOCKER_REGISTRY
    build:
      steps:
        - sh: skaffold version
          name: skaffold-version
        - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
          name: container-build
        - dir: charts/REPLACE_ME_APP_NAME
          steps:
            - sh: jx step helm build
              name: helm-build

  release:
    setup:
      steps:
      - name: docker-config-mkdir
        command: mkdir -p $DOCKER_CONFIG
      - name: docker-config-cp
        command: cp -L /home/jenkins/.docker/config.json $DOCKER_CONFIG/config.json
      - name: azure-login
        command: rpm --import https://packages.microsoft.com/keys/microsoft.asc && echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo && yum install azure-cli -y && curl -L https://aka.ms/acr/installaad/bash | /bin/bash && cp /usr/local/bin/docker-credential-acr-linux /usr/local/bin/docker-credential-acr && az login --identity && az acr login -n  $DOCKER_REGISTRY
    setVersion:
      steps:
        - sh: jx step next-version --use-git-tag-only --tag
          name: tag-with-new-version
    build:
      steps:
        - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
          name: container-build
        - dir: charts/REPLACE_ME_APP_NAME
          steps:
            - sh: jx step helm build --verbose
              name: helm-build
              comment: Let's build chart
    promote:
      steps:
      - dir: charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          name: changelog
        - comment: Let's release the helm chart
          sh: jx step helm release
          name: helm-release
        - comment: Let's promote through all 'Auto' promotion Environments
          sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
          name: jx-promote



