extends:
  import: classic
  file: maven/pipeline.yaml
env:
- name: DOCKER_CONFIG
  value: /home/jenkins/.azure-docker/
- name: AZURE_CONFIG_DIR
  value: /home/jenkins/.azure
pipelines:
  pullRequest:
    setup:
      steps:
      - name: docker-config-mkdir
        command: mkdir -p $DOCKER_CONFIG
      - name: docker-config-cp
        command: cp -L /home/jenkins/.docker/config.json $DOCKER_CONFIG/config.json
      - name: azure-login
        command: rpm --import https://packages.microsoft.com/keys/microsoft.asc && echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo && yum install azure-cli -y && curl -L https://aka.ms/acr/installaad/bash | /bin/bash && cp /usr/local/bin/docker-credential-acr-linux /usr/local/bin/docker-credential-acr && az login --identity && az acr login -n  $DOCKER_REGISTRY
    preBuild:
      steps:
      - args:
        - init
        - --client-only
        - --stable-repo-url
        - https://charts.helm.sh/stable
        command: helm
        dir: ./charts/preview
        name: init-helm2
    build:
      steps:
      - sh: skaffold version
        name: skaffold-version
      - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
        name: container-build
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
        name: post-build
    promote:
      steps:
      - dir: charts/preview
        steps:
        - sh: make preview
          name: make-preview
        - sh: jx preview --app $APP_NAME --dir ../..
          name: jx-preview

  release:
    setup:
      steps:
      - name: docker-config-mkdir
        command: mkdir -p $DOCKER_CONFIG
      - name: docker-config-cp
        command: cp -L /home/jenkins/.docker/config.json $DOCKER_CONFIG/config.json
      - name: azure-login
        command: rpm --import https://packages.microsoft.com/keys/microsoft.asc && echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo && yum install azure-cli -y && curl -L https://aka.ms/acr/installaad/bash | /bin/bash && cp /usr/local/bin/docker-credential-acr-linux /usr/local/bin/docker-credential-acr && az login --identity && az acr login -n  $DOCKER_REGISTRY
    preBuild:
      steps:
      - args:
        - init
        - --client-only
        - --stable-repo-url
        - https://charts.helm.sh/stable
        command: helm
        name: init-helm2
    build:
      steps:
      - sh: skaffold version
        name: skaffold-version
      - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
        name: container-build
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
    promote:
      preSteps:
      - args:
        - init
        - --client-only
        - --stable-repo-url
        - https://charts.helm.sh/stable
        command: helm
        name: init-helm2
     steps:
      - dir: charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          name: changelog
        - comment: release the helm chart
          sh: jx step helm release
          name: helm-release
        - comment: promote through all 'Auto' promotion Environments
          sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
          name: jx-promote
